import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, parseISO } from 'date-fns';
import { GrowthEntry, Gender } from '@/types/baby';

export function exportToCSV(entries: GrowthEntry[], gender: Gender): void {
  const headers = ['Date', 'Weight (kg)', 'Height (cm)'];
  const rows = entries.map(entry => [
    format(parseISO(entry.date), 'yyyy-MM-dd'),
    entry.weight.toString(),
    entry.height.toString(),
  ]);

  const csvContent = [
    `Baby Growth Data - ${gender === 'male' ? 'Boy' : 'Girl'}`,
    `Exported: ${format(new Date(), 'yyyy-MM-dd HH:mm')}`,
    '',
    headers.join(','),
    ...rows.map(row => row.join(',')),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `baby-growth-${gender}-${format(new Date(), 'yyyy-MM-dd')}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToPDF(entries: GrowthEntry[], gender: Gender): void {
  const doc = new jsPDF();
  const genderLabel = gender === 'male' ? 'Boy' : 'Girl';
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(gender === 'male' ? '#60a5fa' : '#f472b6');
  doc.text(`Baby Growth Report - ${genderLabel}`, 14, 20);
  
  // Subtitle
  doc.setFontSize(10);
  doc.setTextColor('#6b7280');
  doc.text(`Generated: ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}`, 14, 28);
  
  // Summary section
  if (entries.length > 0) {
    const latestEntry = entries[entries.length - 1];
    const firstEntry = entries[0];
    
    doc.setFontSize(12);
    doc.setTextColor('#374151');
    doc.text('Summary', 14, 40);
    
    doc.setFontSize(10);
    doc.setTextColor('#6b7280');
    doc.text(`Total entries: ${entries.length}`, 14, 48);
    doc.text(`First recorded: ${format(parseISO(firstEntry.date), 'MMM d, yyyy')}`, 14, 54);
    doc.text(`Latest recorded: ${format(parseISO(latestEntry.date), 'MMM d, yyyy')}`, 14, 60);
    doc.text(`Current weight: ${latestEntry.weight} kg`, 14, 66);
    doc.text(`Current height: ${latestEntry.height} cm`, 14, 72);
    
    // Weight change
    const weightChange = latestEntry.weight - firstEntry.weight;
    const heightChange = latestEntry.height - firstEntry.height;
    doc.text(`Weight gain: ${weightChange >= 0 ? '+' : ''}${weightChange.toFixed(2)} kg`, 14, 78);
    doc.text(`Height gain: ${heightChange >= 0 ? '+' : ''}${heightChange.toFixed(1)} cm`, 14, 84);
  }
  
  // Table
  const tableData = entries.map(entry => [
    format(parseISO(entry.date), 'MMM d, yyyy'),
    `${entry.weight} kg`,
    `${entry.height} cm`,
  ]);
  
  autoTable(doc, {
    startY: entries.length > 0 ? 94 : 40,
    head: [['Date', 'Weight', 'Height']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: gender === 'male' ? [96, 165, 250] : [244, 114, 182],
      textColor: [255, 255, 255],
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    styles: {
      fontSize: 10,
      cellPadding: 4,
    },
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor('#9ca3af');
    doc.text(
      'Generated by Baby Growth Tracker',
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  doc.save(`baby-growth-${gender}-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
}
